// Checkbox component Tailwind styles
// Defines styles for pixel-styled checkbox root and indicator

export const checkboxStyles = {
  root: [
    'font-pixel',
    'transition-none', // No smooth transitions for pixel aesthetic
    'inline-flex',
    'items-center',
    'justify-center',
    'bg-white',
    'dark:bg-nes-gray-dark',
    'border-2',
    'cursor-pointer',
    'outline-none',
    // Disabled state
    'data-[disabled]:cursor-not-allowed',
    'data-[disabled]:opacity-60',
    'data-[disabled]:grayscale',
    'dark:data-[disabled]:opacity-40',
    'dark:data-[disabled]:brightness-75',
    // Read-only state
    'data-[readonly]:cursor-default',
  ].join(' '),

  variants: {
    base: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-black',
      'dark:data-[checked]:bg-nes-white',
      'data-[checked]:border-nes-black',
      'dark:data-[checked]:border-nes-white',
      'data-[indeterminate]:bg-nes-gray',
      'data-[indeterminate]:border-nes-gray',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-black',
      'dark:focus-visible:ring-nes-white',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    primary: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-primary',
      'data-[checked]:border-nes-primary',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.primary)]',
      'data-[indeterminate]:bg-nes-primary',
      'data-[indeterminate]:border-nes-primary',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.primary)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-primary',
      'dark:focus-visible:ring-nes-secondary',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    secondary: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-secondary',
      'data-[checked]:border-nes-secondary',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.secondary)]',
      'data-[indeterminate]:bg-nes-secondary',
      'data-[indeterminate]:border-nes-secondary',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.secondary)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-secondary',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    accent: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-accent',
      'data-[checked]:border-nes-accent',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.accent)]',
      'data-[indeterminate]:bg-nes-accent',
      'data-[indeterminate]:border-nes-accent',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.accent)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-accent',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    ghost: [
      'border-nes-gray',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.gray)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-gray',
      'data-[checked]:border-nes-gray',
      'dark:data-[checked]:border-nes-white',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.gray)]',
      'dark:data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[indeterminate]:bg-nes-gray',
      'data-[indeterminate]:border-nes-gray',
      'dark:data-[indeterminate]:border-nes-white',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.gray)]',
      'dark:data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-gray',
      'dark:focus-visible:ring-nes-white',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.gray)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    error: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-error',
      'data-[checked]:border-nes-error',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.error)]',
      'data-[indeterminate]:bg-nes-error',
      'data-[indeterminate]:border-nes-error',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.error)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-error',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    success: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-success',
      'data-[checked]:border-nes-success',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.success)]',
      'data-[indeterminate]:bg-nes-success',
      'data-[indeterminate]:border-nes-success',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.success)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-success',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    warning: [
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'data-[checked]:bg-nes-warning',
      'data-[checked]:border-nes-warning',
      'data-[checked]:shadow-[2px_2px_0_0_theme(colors.nes.warning)]',
      'data-[indeterminate]:bg-nes-warning',
      'data-[indeterminate]:border-nes-warning',
      'data-[indeterminate]:shadow-[2px_2px_0_0_theme(colors.nes.warning)]',
      'focus-visible:ring-2',
      'focus-visible:ring-nes-warning',
      'focus-visible:ring-offset-2',
      'hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:not([data-disabled]):shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
  },

  sizes: {
    xs: 'w-4 h-4 text-xs', // 16px
    sm: 'w-5 h-5 text-sm', // 20px (new default)
    md: 'w-6 h-6 text-base', // 24px (old default)
    lg: 'w-7 h-7 text-lg', // 28px
    xl: 'w-8 h-8 text-xl', // 32px
  },

  indicator: [
    'flex',
    'items-center',
    'justify-center',
    'w-full',
    'h-full',
    'text-white',
    'font-bold',
    'text-base',
    'leading-none',
  ].join(' '),

  checkmark: [
    // Specific styling for the checkmark character
    'select-none',
    'pointer-events-none',
  ].join(' '),
}
