// Textarea component Tailwind styles
// Defines base, variant, and size styles for pixel-styled textarea

export const textareaStyles = {
  base: [
    'font-pixel',
    'transition-none', // No smooth transitions for pixel aesthetic
    'w-full',
    'outline-none',
    'focus:outline-none',
    'disabled:cursor-not-allowed',
    'disabled:opacity-60',
    'disabled:grayscale',
    'dark:disabled:opacity-40',
    'dark:disabled:brightness-75',
    'read-only:cursor-default',
    'read-only:bg-nes-gray/10',
    'placeholder:text-nes-gray',
    'data-[invalid]:border-nes-error',
    'data-[invalid]:text-nes-error',
    'resize-none', // Disable browser resize for pixel aesthetic
  ].join(' '),

  variants: {
    base: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:shadow-[3px_3px_0_0_theme(colors.nes.white)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:focus:shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    primary: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-primary',
      'shadow-[2px_2px_0_0_theme(colors.nes.primary)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.primary)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.primary)]',
    ].join(' '),
    secondary: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-secondary',
      'shadow-[2px_2px_0_0_theme(colors.nes.secondary)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.secondary)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.secondary)]',
    ].join(' '),
    accent: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-accent',
      'shadow-[2px_2px_0_0_theme(colors.nes.accent)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.accent)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.accent)]',
    ].join(' '),
    ghost: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-gray',
      'shadow-[2px_2px_0_0_theme(colors.nes.gray)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.gray)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.gray)]',
    ].join(' '),
    error: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-error',
      'shadow-[2px_2px_0_0_theme(colors.nes.error)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.error)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.error)]',
    ].join(' '),
    success: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-success',
      'shadow-[2px_2px_0_0_theme(colors.nes.success)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.success)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.success)]',
    ].join(' '),
    warning: [
      'bg-white',
      'dark:bg-nes-gray-dark',
      'text-nes-black',
      'dark:text-nes-white',
      'border-2',
      'border-nes-warning',
      'shadow-[2px_2px_0_0_theme(colors.nes.warning)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.warning)]',
      'focus:shadow-[3px_3px_0_0_theme(colors.nes.warning)]',
    ].join(' '),
  },

  sizes: {
    xs: 'min-h-xs px-2 py-1 text-xs',
    sm: 'min-h-sm px-3 py-2 text-sm',
    md: 'min-h-md px-4 py-3 text-base',
    lg: 'min-h-lg px-6 py-4 text-lg',
    xl: 'min-h-xl px-8 py-5 text-xl',
  },
}
