// Button component Tailwind styles
// Defines base, variant, and size styles for pixel-styled button

export const buttonStyles = {
  base: [
    'font-pixel',
    'transition-none', // No smooth transitions for pixel aesthetic
    'cursor-pointer',
    'select-none',
    'inline-flex',
    'items-center',
    'justify-center',
    'border-2',
    'active:translate-y-px', // Pixel "press" effect
    'disabled:cursor-not-allowed',
    'disabled:opacity-60',
    'disabled:grayscale',
    'dark:disabled:opacity-40',
    'dark:disabled:brightness-75',
  ].join(' '),

  variants: {
    base: [
      'bg-nes-black',
      'dark:bg-nes-white',
      'text-white',
      'dark:text-black',
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:shadow-[3px_3px_0_0_theme(colors.nes.white)]',
      'hover:brightness-90',
    ].join(' '),
    primary: [
      'bg-nes-primary',
      'text-white',
      'border-nes-primary',
      'shadow-[2px_2px_0_0_theme(colors.nes.primary)]',
      'hover:bg-nes-primary-hover',
      'hover:border-nes-primary-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.primary-hover)]',
    ].join(' '),
    secondary: [
      'bg-nes-secondary',
      'text-white',
      'border-nes-secondary',
      'shadow-[2px_2px_0_0_theme(colors.nes.secondary)]',
      'hover:bg-nes-secondary-hover',
      'hover:border-nes-secondary-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.secondary-hover)]',
    ].join(' '),
    accent: [
      'bg-nes-accent',
      'text-black',
      'border-nes-accent',
      'shadow-[2px_2px_0_0_theme(colors.nes.accent)]',
      'hover:bg-nes-accent-hover',
      'hover:border-nes-accent-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.accent-hover)]',
      'hover:text-white',
    ].join(' '),
    ghost: [
      'bg-transparent',
      'text-nes-black',
      'dark:text-nes-white',
      'border-nes-black',
      'dark:border-nes-white',
      'shadow-[2px_2px_0_0_theme(colors.nes.black)]',
      'dark:shadow-[2px_2px_0_0_theme(colors.nes.white)]',
      'hover:bg-nes-gray/10',
      'dark:hover:bg-nes-white/10',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.black)]',
      'dark:hover:shadow-[3px_3px_0_0_theme(colors.nes.white)]',
    ].join(' '),
    error: [
      'bg-nes-error',
      'text-white',
      'border-nes-error',
      'shadow-[2px_2px_0_0_theme(colors.nes.error)]',
      'hover:bg-nes-error-hover',
      'hover:border-nes-error-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.error-hover)]',
    ].join(' '),
    success: [
      'bg-nes-success',
      'text-black',
      'border-nes-success',
      'shadow-[2px_2px_0_0_theme(colors.nes.success)]',
      'hover:bg-nes-success-hover',
      'hover:border-nes-success-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.success-hover)]',
    ].join(' '),
    warning: [
      'bg-nes-warning',
      'text-black',
      'border-nes-warning',
      'shadow-[2px_2px_0_0_theme(colors.nes.warning)]',
      'hover:bg-nes-warning-hover',
      'hover:border-nes-warning-hover',
      'hover:shadow-[3px_3px_0_0_theme(colors.nes.warning-hover)]',
    ].join(' '),
  },

  sizes: {
    xs: 'h-xs px-2 text-xs gap-1',
    sm: 'h-sm px-3 text-sm gap-1',
    md: 'h-md px-4 text-base gap-2',
    lg: 'h-lg px-6 text-lg gap-2',
    xl: 'h-xl px-8 text-xl gap-3',
  },

  loading: 'opacity-75 cursor-wait',
}
